site_name: Guia de Transparência Ativa

# Repository
repo_name: transparencia-mg/guia-transparencia-ativa
repo_url: http://github.com/transparencia-mg/guia-transparencia-ativa
edit_uri: edit/review/docs/

nav:
  - 1 INTRODUÇÃO: 'index.md'
  - 2 ORGANIZAÇÃO DOS CONTEÚDOS: 'organizacao-dos-conteudos.md'
  - 3 MENU TRANSPARÊNCIA: 'menu-transparencia.md'
  - 4 DIVULGAÇÃO OBRIGATÓRIA: 
    - 4.1 Serviço de Informação ao Cidadão: 'servico-informacao.md'
    - 4.2 Informações Classificadas e Desclassificadas: 'informacoes-classificadas.md'
    - 4.3 Relatório de Gestão: 'relatorio-gestao.md'
    - 4.4 Programas e Ações: 'programas-acoes.md'
    - 4.5 Obras Públicas: 'obras-publicas.md'
    - 4.6 Despesas e receitas: 'despesas-receitas.md'
    - 4.6.1 Ordem Cronológica de Pagamento: 'ordem-cronologica.md'
    - 4.7 Compras e Contratos: 'compras-contratos.md'
    - 4.7.1 Fiscais de Contratos: 'fiscais-contratos.md'
    - 4.8 Convênios, Repasses e Transferências: 'convenios-repasses.md'
    - 4.9 Convênios de Entrada: 'convenios-entrada.md'
    - 4.10 Servidores: 'servidores.md'
    - 4.11 Concursos Públicos: 'concursos-publicos.md'
    - 4.12 Dados Abertos: 'dados-abertos.md'
  - 5 DIVULGAÇÃO ESPECÍFICA:
    - 5.1 Procedimentos licitatórios enviados para o TCE/MG: 'tce.md'
    - 5.2 Doações e Comodatos: 'doacoes.md'
  - 6 DIVULGAÇÃO OPCIONAL: 
    - 6.1 Participação Social: 'participacao-social.md'
    - 6.2 Bens: 'bens.md'
  - 7 DISPOSITIVOS LEGAIS: 'dispositivos-legais.md'
  - 8 ASPECTOS TECNOLÓGICOS: 'aspectos-tecnologicos.md'
  - 9 CHECKLIST: 'checklist.md'

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - abbr
  - footnotes
  - attr_list
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md

extra_css:
  - assets/style.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - assets/style.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

extra: # Footer
  social:
    - icon: fontawesome/brands/youtube
      name: Canal Transparência-MG YouTube.
      link: https://www.youtube.com/@transparenciamg2235
    - icon: fontawesome/solid/flag
      name: Material for MkDocs Icons, Emojis.
      link: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
    - icon: fontawesome/brands/github-alt
      name: Repositório GitHub da documentação.
      link: https://github.com/transparencia-mg/guia-transparencia-ativa
  version:
    provider: mike

plugins:
  - git-revision-date-localized:
      enable_creation_date: true 
      type: datetime
      enable_creation_date: true
  - mike:
      version_selector: true
