site_name: Guia de Transparência Ativa

# Repository
repo_name: transparencia-mg/guia-transparencia-ativa
repo_url: http://github.com/transparencia-mg/guia-transparencia-ativa
edit_uri: edit/main/docs/

nav:
  - 1 INTRODUÇÃO: 'index.md'
  - 2 ORGANIZAÇÃO DOS CONTEÚDOS: 'organizacao-dos-conteudos.md'
  - 3 MENU TRANSPARÊNCIA: 'menu-transparencia.md'
  - 4 DIVULGAÇÃO OBRIGATÓRIA: 
    - 4.1 Serviço de Informação ao Cidadão: 'servico-informacao.md'
    - 4.2 Informações Classificadas e Desclassificadas: 'informacoes-classificadas.md'
    - 4.3 Programas e Ações: 'programas-acoes.md'
  - 6 DIVULGAÇÃO OPCIONAL: 
    - 6.1 Participação Social: 'participacao-social.md'
    - 6.2 Convênios de Entrada: 'convenios-entrada.md'
    - 6.3 Bens: 'bens.md'
  - 7 DISPOSITIVOS LEGAIS: 'dispositivos-legais.md'
  - 8 ASPECTOS TECNOLÓGICOS: 'aspectos-tecnologicos.md'
  - 9 CHECKLIST: 'checklist.md'
# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
